### ISSUE TITLE
Configuration compatibility with MIT implementation

### ISSUE THREAD

**Issue by undecided2013** [dotnet/Kerberos.NET#126]
Trying to use a .net core application in a linux container against existing kerberos infrastructure.
Most documentation for apps in that situation indicate the need for using keytab files and rely on the MIT command line tools to set everything up.
The kdc information is in the /etc/krb5.conf.
It seems that  the ASPNetCore team also uses that for their Negotiate mechanism. It would be nice if Kerberos.Net also did.

KerberosClient should provide an initialization mechanism that consumes the same krb5.conf.

I am going to be doing this in my client right now but with some guidance I could contribute whatever I do if wanted.

Thx

**Comment by SteveSyfuhs** [comment]
To what end? To just read in the config for which KDCs and keytab files to use? That would certainly be an interesting and useful feature to add. The krb5.conf is an interesting format and I haven't really thought about how to parse it correctly. If you have ideas they'd certainly be welcome.

**Comment by SteveSyfuhs** [comment]
Configuration support has been added in client and some KDC bits.
